# Generated by Django 2.0.4 on 2018-04-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateTimeField(verbose_name='quotation date')),
                ('room_date', models.DateTimeField(verbose_name='room date')),
                ('room_type', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=20)),
                ('quoted_price', models.IntegerField(default=-1)),
            ],
        ),
    ]
