# Generated by Django 2.0.4 on 2018-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgm_scrapper', '0002_auto_20180424_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
